apiVersion: batch/v1
kind: Job
metadata:
  name: request-generator
spec:
  parallelism: 10
  template:
    metadata:
      name: request-generator
    spec:
      containers:
      - name: request-generator
        image: dongyiyang/requestgenerator:0.1
        command:
          - /bin/requestgenerator
        args:
          - --v=3
          - --host=http://simple-server:9090
          - --duration=30
          - --qps=1
      restartPolicy: Never

