apiVersion: v1
kind: ReplicationController
metadata:
  name: request-generator
  labels:
    name: request-generator
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: request-generator
    spec:
      containers:
      - name: request-generator
        image: dongyiyang/requestgenerator:latest
        command:
          - /bin/requestgenerator
        args:
          - --v=3
          - --host=http://simple-server:9090
          - --qps=1
      restartPolicy: Always

